taskmanager/views.py
# Copyright 2017 Biomedical Imaging Group Rotterdam, Departments of
# Medical Informatics and Radiology, Erasmus MC, Rotterdam, The Netherlands
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_security import current_user
from flask_security import login_required
from flask_security import permissions_required
from flask_security import permissions_accepted

from flask import current_app

from . import models


# Create the web blueprint
bp = Blueprint('web', __name__)


@bp.app_errorhandler(404)
def page_not_found_error(error):
    title = f'Taskmanager: 404 Not Found'
    return render_template('error/notfound.html', title=title), 404


@bp.errorhandler(403)
def forbidden_error(error):
    title = f'Taskmanager: 403 Forbidden'
    return render_template('error/forbidden.html', title=title), 404


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')


@bp.route('/tasks')
@login_required
@permissions_accepted('task_read', 'task_read_all')
def tasks():
    query = models.Task.query
    if not current_user.has_permission('task_read_all'):
        tasks_via_user_query = query.filter(models.Task.users.contains(current_user))
        tasks_via_group_query = query.filter(models.Task.users_via_group.contains(current_user))
        query = tasks_via_user_query.union(tasks_via_group_query)
    data = query.order_by(models.Task.id.asc()).all()
    return render_template('tasks.html', data=data)


@bp.route('/tasks/<int:id>')
@login_required
@permissions_accepted('task_read', 'task_read_all')
def task(id):
    query = models.Task.query.filter(models.Task.id == id)
    if not current_user.has_permission('task_read_all'):
        tasks_via_user_query = query.filter(models.Task.users.contains(current_user))
        tasks_via_group_query = query.filter(models.Task.users_via_group.contains(current_user))
        query = tasks_via_user_query.union(tasks_via_group_query)
    data = query.one_or_none()

    if data is None:
        abort(404)

    return render_template('task.html', data=data)


@bp.route('/taskgroups')
@login_required
@permissions_accepted('task_read', 'task_read_all')
def taskgroups():
    data = models.TaskGroup.query.order_by(models.TaskGroup.id.asc()).all()
    if data is None:
        abort(404)
    return render_template('taskgroups.html', data=data)


@bp.route('/taskgroups/<int:id>')
@login_required
@permissions_accepted('task_read', 'task_read_all')
def taskgroup(id):
    data = models.TaskGroup.query.filter(models.TaskGroup.id == id).one_or_none()
    if data is None:
        abort(404)
    return render_template('taskgroup.html', data=data)


@bp.route('/templates')
@login_required
def templates():
    data = models.TaskTemplate.query.all()
    return render_template('templates.html', data=data)


@bp.route('/templates/<int:id>')
@login_required
def template(id):
    data = models.TaskTemplate.query.filter(models.TaskTemplate.id == id).one_or_none()

    # Count the tasks per template for this user
    users = models.User.query.all()

    counts_per_user = []
    for user in users:
        tasks_via_user_query = models.Task.query.filter(models.Task.users.contains(user))
        tasks_via_group_query = models.Task.query.filter(models.Task.users_via_group.contains(user))
        all_tasks_query = tasks_via_user_query.union(tasks_via_group_query)
        template_query = all_tasks_query.filter(models.Task.template == data)

        count_data = {
            'user_id': user.id,
            'user': user.username,
            'tasks': template_query.count(),
            'tasks_queued': template_query.filter(models.Task._status == 'queued').count(),
        }
        if count_data['tasks'] > 0:
            counts_per_user.append(count_data)

    if data is None:
        abort(404)
    return render_template('template.html', data=data, counts_per_user=counts_per_user)


@bp.route('/users')
@login_required
@permissions_accepted('user_read_all')
def users():
    data = models.User.query.all()

    return render_template('users.html', data=data)


@bp.route('/users/roles')
@login_required
@permissions_accepted('roles_manage')
def userroles():
    data = models.User.query.all()
    roles = models.Role.query.order_by(models.Role.id).all()
    return render_template('userroles.html', data=data, roles=roles)


@bp.route('/users/<int:id>')
@login_required
@permissions_accepted('user_read', 'user_read_all')
def user(id):
    data = models.User.query.filter(models.User.id == id).one_or_none()
    if data is None:
        abort(404)

    if not current_user.has_permission('user_read_all'):
        # This is a normal user, so may only see own user information.
        if current_user != data:
            abort(403)

    # Count the tasks per template for this user
    templates = models.TaskTemplate.query.all()

    tasks_via_user_query = models.Task.query.filter(models.Task.users.contains(data))
    tasks_via_group_query = models.Task.query.filter(models.Task.users_via_group.contains(data))
    all_tasks_query = tasks_via_user_query.union(tasks_via_group_query)

    counts_per_template = []
    for template in templates:
        template_query = all_tasks_query.filter(models.Task.template == template)
        count_data = {
            'template_id': template.id,
            'template': template.label,
            'tasks': template_query.count(),
            'tasks_queued': template_query.filter(models.Task._status == 'queued').count(),
        }
        if count_data['tasks'] > 0:
            counts_per_template.append(count_data)

    return render_template('user.html', data=data, counts_per_template=counts_per_template)


@bp.route('/groups')
@login_required
@permissions_accepted('group_read_all')
def groups():
    data = models.Group.query.all()
    return render_template('groups.html', data=data)


@bp.route('/groups/<int:id>')
@login_required
@permissions_accepted('group_read', 'group_read_all')
def group(id):
    data = models.Group.query.filter(models.Group.id == id).one_or_none()
    if data is None:
        abort(404)

    if not current_user.has_permission('group_read_all'):
        if data not in current_user.groups:
            abort(403)

    return render_template('group.html', data=data)


@bp.route('/tags')
@login_required
@permissions_accepted('task_read', 'task_read_all')
def tags():
    data = models.Tag.query.order_by(models.Tag.id).all()
    return render_template('tags.html', data=data)


@bp.route('/tags/<int:id>')
@login_required
@permissions_accepted('task_read_all')
def tag(id):
    data = models.Tag.query.filter(models.Tag.id == id).one_or_none()
    if data is None:
        abort(404)

    return render_template('tag.html', data=data)

taskmanager/templates/group.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}

{% block content %}

<h1>Group {{data.name}} </h1>
{{ collapse_card_start("Group Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>groupname</dt>
        <dd>{{ data.groupname }}</dd>

        <dt>name</dt>
        <dd>{{ data.name }}</dd>

        <dt>create time</dt>
        <dd>{{ data.create_time }}</dd>
      </dl>
{{ collapse_card_end("Group Information") }}

{% if data.users %}
{{ collapse_card_start("Group Members", show=True, data_count=data.users|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th></th>
          <th>name</th>
        </tr>
        </thead>
        <tbody>
        {% for user in data.users|sort(attribute='id') %}
        <tr>
          <td>
            {{user.id}}
          </td>
          <td>
            <a href="{{url_for('web.user', id=user.id)}}">{{user.name}}</a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Group Members") }}
{% endif %}

{% if data.tasks %}
{{ collapse_card_start("Tasks Assigned to Group", show=True, data_count=data.tasks|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>status</th>
          <th>lock</th>
          <th>project</th>
          <th>create time</th>
          <th>update time</th>
        </tr>
        </thead>
        <tbody>
        {% for d in data.tasks|sort(attribute='id') %}
        <tr>
          <td>
            <a href="{{url_for('web.task', id=d.id) }}">
              {{d.id}}
            </a>
          </td>
          <td>{{d.status}}</td>
          <td>
            {% if d.lock %}
            <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
            {% endif %}
          </td>
          <td>{{d.project}}</td>
          <td>{{d.create_time}}</td>
          <td>{{d.update_time}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Tasks Assigned to Group") }}
{% endif %}

{% endblock %}

taskmanager/templates/tag.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}

{% block content %}

<h1>Tag {{data.name}} </h1>
{{ collapse_card_start("Tag Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>name</dt>
        <dd>{{ data.name }}</dd>

        <dt># of tasks</dt>
        <dd>
          {{ card_link_by_title("Tasks") }}
            <span class="badge badge-secondary">{{ data.tasks|length }}</span>
          </a>
        </dd>
      </dl>
{{ collapse_card_end("Tag Information") }}

{% if data.tasks %}
{{ collapse_card_start("Tasks", show=True, data_count=data.tasks|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>status</th>
          <th>lock</th>
          <th>project</th>
          <th>create time</th>
          <th>update time</th>
        </tr>
        </thead>
        <tbody>
        {% for d in data.tasks|sort(attribute='id') %}
        <tr>
          <td>
            <a href="{{url_for('web.task', id=d.id) }}">
              {{d.id}}
            </a>
          </td>
          <td>{{d.status}}</td>
          <td>
            {% if d.lock %}
            <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
            {% endif %}
          </td>
          <td>{{d.project}}</td>
          <td>{{d.create_time}}</td>
          <td>{{d.update_time}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Tasks") }}
{% endif %}

{% endblock %}

taskmanager/templates/task.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}

{% block content %}


<h1>Task {{ data.id }} </h1>
{{ collapse_card_start("Task Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>status</dt>
        <dd>{{ data.status }}</dd>

        <dt>lock</dt>
        <dd>
          {% if data.lock %}
              <a href="{{url_for('web.user', id=data.lock.id)}}">{{data.lock.name}}</a>
          {% endif %}
        </dd>

        <dt>project</dt>
        <dd>{{ data.project }}</dd>

        <dt>template</dt>
        {% if data.template %}
        <dd><a href="{{url_for('web.template', id=data.template.id)}}">
            {{ data.template.label }}
            </a>
        </dd>
        {% endif %}

        <dt>task group</dt>
        <dd>
        {% if data.parent %}
          <a href="{{url_for('web.taskgroup', id=data.parent.id)}}">
            {% if data.parent.label %}
              {{ data.parent.label }}
            {% else %}
              {{ data.parent.id }}
            {% endif %}
          </a>
        {% endif %}
        </dd>

        <dt>generator_url</dt>
        <dd>
        {% if data.generator_url %}
        <a href="{{ data.generator_url }}">
            {{ data.generator_url }}
            </a>
        {% endif %}
        </dd>

        <dt>application name</dt>
        <dd>
            {% if data.application_name %}
              {{ data.application_name }}
            {% endif %}
        </dd>

        <dt>application version</dt>
        <dd>
            {% if data.application_version %}
              {{ data.application_version }}
            {% endif %}
        </dd>

        <dt>create time</dt>
        <dd>{{ data.create_time }}</dd>

        <dt>update time</dt>
        <dd>{{ data.update_time }}</dd>

        <dt>tags</dt>
        <dd>
          {% for tag in data.tags %}
            <a href="{{ url_for('web.tag', id=tag.id) }}">
                <span class="badge badge-primary">{{ tag.name }}</span>
            </a>
          {% endfor %}
        </dd>

        <dt># users</dt>
        <dd>
            {{ card_link_by_title("Users") }}
                <span class="badge badge-secondary">{{ data.users | length }}</span>
            </a>
        </dd>

        <dt># groups</dt>
        <dd>
            {{ card_link_by_title("Groups") }}
                <span class="badge badge-secondary">{{ data.groups | length }}</span>
            </a>
        </dd>

        <dt># users via groups</dt>
        <dd>
            {{ card_link_by_title("Users via Group") }}
                <span class="badge badge-secondary">{{ data.users_via_group | length }}</span>
            </a>
        </dd>

        <dt>content</dt>
        <dd>
            {% if data.content %}
            <pre class="language-json line-numbers"><code>{{ data.content | json_format }}</code></pre>
            {% endif %}
        </dd>
      </dl>
{{ collapse_card_end("Task Information") }}

{% if data.callback_url %}
{{ collapse_card_start("Callback Information", show=False) }}
          <dl class="dl-horizontal">
              <dt>callback url</dt>
              <dd>{{ data.callback_url }}</dd>
          </dl>
          <dl class="dl-horizontal">
              <dt>callback content</dt>
              <dd>
                  <pre class="language-json line-numbers"><code>{{ data.callback_content | json_format }}</code></pre>
              </dd>
          </dl>
{{ collapse_card_end("Callback Information") }}
{% endif %}

{% if data.users %}
{{ collapse_card_start("Users", show=True, data_count=data.users|length) }}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th></th>
                    <th>name</th>
                </tr>
                </thead>
                <tbody>
                {% for user in data.users %}
                <tr>
                    <td>
                        {{user.id}}
                    </td>
                    <td>
                        <a href="{{url_for('web.user', id=user.id)}}">{{user.name}}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
{{ collapse_card_end("Users") }}
{% endif %}

{% if data.groups %}
{{ collapse_card_start("Groups", show=True, data_count=data.groups|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>users</th>
        </tr>
        </thead>
        <tbody>
        {% for group in data.groups %}
        <tr>
          <td>
              {{group.id}}
          </td>
          <td>
              <a href="{{url_for('web.group', id=group.id)}}">{{group.name}}</a>
          </td>
          <td>
              {{group.users | join(', ', attribute='name')}}
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Groups") }}

{% endif %}

{% if data.users_via_group %}
{{ collapse_card_start("Users via Group", show=True, data_count=data.users_via_group|length) }}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>user groups</th>
                </tr>
                </thead>
                <tbody>
                {% for user in data.users_via_group %}
                <tr>
                    <td>
                        {{user.id}}
                    </td>
                    <td>
                        <a href="{{url_for('web.user', id=user.id)}}">{{user.name}}</a>
                    </td>
                    <td>
                        {{user.groups | join(', ', attribute='name')}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
{{ collapse_card_end("Users via Group") }}
{% endif %}

{% endblock %}

taskmanager/templates/taskgroup.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}
{% block content %}


<h1>TaskGroup {{data.label}} </h1>

{{ collapse_card_start("Taskgroup Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>label</dt>
        <dd>{{ data.label }}</dd>

        <dt>status</dt>
        <dd>{{ data.status }}</dd>

        <dt># tasks</dt>
        <dd>
            {{ card_link_by_title("Tasks")}}
                <span class="badge badge-secondary">{{ data.tasks | length }}</span>
            </a>
        </dd>

        <dt># queued tasks</dt>
        <dd>
            {{ card_link_by_title("Tasks")}}
                <span class="badge badge-secondary">{{ data.tasks | selectattr("status", "equalto", "queued") | list | length }}</span>
            </a>
        </dd>
      </dl>
{{ collapse_card_end("Taskgroup Information") }}

{% if data.callback_url %}
{{ collapse_card_start("Callback Information", show=True) }}
          <dl class="dl-horizontal">
              <dt>callback url</dt>
              <dd><a href="{{ data.callback_url }}">{{ data.callback_url }}</a></dd>
          </dl>
          <dl class="dl-horizontal">
              <dt>callback called</dt>
              <dd>
                <span class="badge badge-{{ 'success' if data.callback_fired else 'danger' }}">
                  {{data.callback_fired}}
                </span>
              </dd>
          </dl>
          <dl class="dl-horizontal">
              <dt>callback content</dt>
              <dd>
                  <pre class="language-json line-numbers"><code>{{ data.callback_content | json_format }}</code></pre>
              </dd>
          </dl>
{{ collapse_card_end("Callback Information") }}
{% endif %}

{% if data.tasks %}
<h1>Tasks Overview</h1>
{{ collapse_card_start("Tasks", show=True, data_count=data.tasks|length) }}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>status</th>
                    <th>lock</th>
                    <th>project</th>
                    <th>application name</th>
                    <th>application version</th>
                    <th>template</th>
                    <th>create time</th>
                    <th>update time</th>
                </tr>
                </thead>
                <tbody>
                {% for d in data.tasks %}
                <tr>
                    <td>
                        <a href="{{url_for('web.task', id=d.id) }}">
                            {{d.id}}
                        </a>
                    </td>
                    <td>{{d.status}}</td>
                    <td>
                        {% if d.lock %}
                        <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
                        {% endif %}
                    </td>
                    <td>{{d.project}}</td>
                    <td>{% if d.application_name %} {{d.application_name}} {% endif %}</td>
                    <td>{% if d.application_version %} {{d.application_version}} {% endif %}</td>
                    <td>{{d.template.label}}</td>
                    <td>{{d.create_time}}</td>
                    <td>{{d.update_time}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
{{ collapse_card_end("Tasks") }}
{% endif %}

{% endblock %}

taskmanager/templates/tasks.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end %}

{% block content %}


<h1>Tasks Overview</h1>
  {{ collapse_card_start("Tasks", show=True) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>status</th>
          <th>lock</th>
          <th>project</th>
          <th>application name</th>
          <th>application version</th>
          <th>template</th>
          <th>create time</th>
          <th>update time</th>
        </tr>
        </thead>
        <tbody>
        {% for d in data %}
        <tr>
          <td>
            <a href="{{url_for('web.task', id=d.id) }}">
              {{d.id}}
            </a>
          </td>
          <td>{{d.status}}</td>
          <td>
              {% if d.lock %}
                  <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
              {% endif %}
          </td>
          <td>{{d.project}}</td>
          <td>{% if d.application_name %} {{d.application_name}} {% endif %}</td>
          <td>{% if d.application_version %} {{d.application_version}} {% endif %}</td>
          <td>
            {% if d.template %}
              <a href="{{ url_for('web.template', id=d.template.id) }}">{{d.template.label}}</a>
            {% endif %}
          </td>
          <td>{{d.create_time}}</td>
          <td>{{d.update_time}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
  {{ collapse_card_end("Tasks") }}

{% endblock %}

taskmanager/templates/template.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}

{% block content %}

<h1>Task Template {{ data.label }} </h1>
{{ collapse_card_start("Template Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>label</dt>
        <dd>{{ data.label }}</dd>

        <dt># tasks</dt>
        <dd>
          {{ card_link_by_title("Tasks")}}
            <span class="badge badge-secondary">{{ data.tasks | length }}</span>
          </a>
        </dd>

        <dt># queued tasks</dt>
        <dd>
          {{ card_link_by_title("Tasks")}}
            <span class="badge badge-secondary">{{ data.tasks | selectattr("status", "equalto", "queued") | list | length }}</span>
          </a>
        </dd>
      </dl>
{{ collapse_card_end("Template Information") }}


{% if data.tasks %}
{{ collapse_card_start("Task Count per User", show=True, data_count=counts_per_user|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>user</th>
          <th># of tasks</th>
          <th># of queued tasks</th>
        </tr>
        </thead>
        <tbody>
        {% for u in counts_per_user|sort(attribute='user_id') %}
        <tr>
          <td>{{ u['user_id'] }}</td>
          <td><a href="{{url_for('web.template', id=u['user_id']) }}">{{u['user']}}</a></td>
          <td>
            {{ card_link_by_title(title="Tasks per Template", prefix=url_for('web.user', id=u['user_id'])) }}
              <span class="badge badge-secondary">{{ u['tasks'] }}</span>
            </a>
          </td>
          <td>
            {{ card_link_by_title(title="Tasks Assigned", prefix=url_for('web.user', id=u['user_id'])) }}
              <span class="badge badge-secondary">{{u['tasks_queued']}}</span>
            </a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Task Count per User") }}

{{ collapse_card_start("Tasks", show=True, data_count=data.tasks|length) }}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>id</th>
            <th>status</th>
            <th>lock</th>
            <th>project</th>
            <th>create time</th>
            <th>update time</th>
          </tr>
        </thead>
        <tbody>
          {% for d in data.tasks|sort(attribute='id') %}
          <tr>
            <td>
              <a href="{{url_for('web.task', id=d.id) }}">
                {{d.id}}
              </a>
            </td>
            <td>{{d.status}}</td>
            <td>
                {% if d.lock %}
                    <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
                {% endif %}
            </td>
            <td>{{d.project}}</td>
            <td>{{d.create_time}}</td>
            <td>{{d.update_time}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Tasks") }}
{% endif %}

{% if data.content %}
{{ collapse_card_start("Content JSON", show=True) }}
      <dl class="dl-horizontal">
        <dt>content</dt>
        <dd>
          <pre class="language-json line-numbers"><code>{{ data.content | json_format }}</code></pre>
        </dd>
      </dl>
{{ collapse_card_end("Content JSON") }}
{% endif %}

{% endblock %}

taskmanager/templates/user.html
{% extends "base.html" %}
{% from "_macros.html" import collapse_card_start, collapse_card_end, card_link_by_title %}

{% block content %}

<h1>User {{ data.name }}</h1>
{{ collapse_card_start("User Information", show=True) }}
      <dl class="dl-horizontal">
        <dt>id</dt>
        <dd>{{ data.id }}</dd>

        <dt>username</dt>
        <dd>{{ data.username }}</dd>

        <dt>name</dt>
        <dd>{{ data.name }}</dd>

        <dt>active</dt>
        <dd>
          <span class="badge badge-{{ 'success' if data.active else 'danger' }}">
            {{ data.active }}
          </span>
        </dd>

        <dt>email</dt>
        <dd>
          {% if data.email %}
          <a href="mailto:{{data.email}}">
            {{ data.email }}
          </a>
          {% endif %}
        </dd>

        <dt>assignment weight</dt>
        <dd>{{ data.assignment_weight }}</dd>

        <dt>create time</dt>
        <dd>{{ data.create_time }}</dd>
      </dl>
{{ collapse_card_end("User Information") }}


{% if data.groups %}
{{ collapse_card_start("Groups", show=True, data_count=data.groups|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>users</th>
        </tr>
        </thead>
        <tbody>
        {% for group in data.groups %}
        <tr>
          <td>
            {{group.id}}
          </td>
          <td>
            <a href="{{url_for('web.group', id=group.id)}}">{{group.name}}</a>
          </td>
          <td>
          {% for user in group.users %}
            {{ ", " if not loop.first }}
            <a href="{{ url_for('web.user', id=user.id) }}">
              {{ user.name }}
            </a>
          {% endfor %}
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Groups") }}
{% endif %}

{% if data.tasks %}
{{ collapse_card_start("Tasks per Template", show=True, data_count=counts_per_template|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>template</th>
          <th># of tasks</th>
          <th># of queued tasks</th>
        </tr>
        </thead>
        <tbody>
        {% for t in counts_per_template|sort(attribute='template_id') %}
        <tr>
          <td>{{ t['template_id'] }}</td>
          <td><a href="{{url_for('web.template', id=t['template_id']) }}">{{t['template']}}</a></td>
          <td><span class="badge badge-secondary">{{t['tasks']}}</span></td>
          <td><span class="badge badge-secondary">{{t['tasks_queued']}}</span></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Tasks per Template") }}

{{ collapse_card_start("Tasks Assigned", show=True, data_count=data.tasks|length) }}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>status</th>
          <th>lock</th>
          <th>project</th>
          <th>create time</th>
          <th>update time</th>
        </tr>
        </thead>
        <tbody>
        {% for d in data.tasks|sort(attribute='id') %}
        <tr>
          <td>
            <a href="{{url_for('web.task', id=d.id) }}">
              {{d.id}}
            </a>
          </td>
          <td>{{d.status}}</td>
          <td>
            {% if d.lock %}
            <a href="{{url_for('web.user', id=d.lock.id)}}">{{d.lock.name}}</a>
            {% endif %}
          </td>
          <td>{{d.project}}</td>
          <td>{{d.create_time}}</td>
          <td>{{d.update_time}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
{{ collapse_card_end("Tasks Assigned") }}
{% endif %}

{% endblock %}